server:
  port: 8761

spring:
  application:
    name: discoveryservice

  cloud:
    config:
      uri: http://127.0.0.1:8889
      name: service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true